/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 C:\Users\USER\OneDrive\Documentos\TI22\HydroSquad\src\assets\textures\111.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pre1(props) {
  const { nodes, materials } = useGLTF('src/assets/textures/pre1.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cube.geometry} material={nodes.cube.material} />
      <mesh geometry={nodes.sphere.geometry} material={nodes.sphere.material} rotation={[-Math.PI, 1.562, -Math.PI]} />
      <mesh geometry={nodes.sphere_1.geometry} material={nodes.sphere_1.material} rotation={[-Math.PI, 1.562, -Math.PI]} />
      <mesh geometry={nodes.sphere_2.geometry} material={nodes.sphere_2.material} rotation={[-Math.PI, 1.562, -Math.PI]} />
      <mesh geometry={nodes.sphere_3.geometry} material={nodes.sphere_3.material} />
      <mesh geometry={nodes.pyramid_2.geometry} material={nodes.pyramid_2.material} />
      <mesh geometry={nodes.pyramid_3.geometry} material={nodes.pyramid_3.material} />
      <mesh geometry={nodes.cube_3.geometry} material={nodes.cube_3.material} />
      <mesh geometry={nodes.cube_4.geometry} material={nodes.cube_4.material} />
      <mesh geometry={nodes.cube_5.geometry} material={nodes.cube_5.material} />
      <mesh geometry={nodes.cube_6.geometry} material={nodes.cube_6.material} />
      <mesh geometry={nodes.cube_7.geometry} material={nodes.cube_7.material} />
      <mesh geometry={nodes.cube_8.geometry} material={nodes.cube_8.material} />
      <mesh geometry={nodes.cube_9.geometry} material={nodes.cube_9.material} />
      <mesh geometry={nodes.cube_10.geometry} material={nodes.cube_10.material} />
      <mesh geometry={nodes.cube_11.geometry} material={nodes.cube_11.material} />
      <mesh geometry={nodes.cube_12.geometry} material={nodes.cube_12.material} />
      <mesh geometry={nodes.cube_13.geometry} material={nodes.cube_13.material} />
      <mesh geometry={nodes.cube_14.geometry} material={nodes.cube_14.material} />
      <mesh geometry={nodes.cube_15.geometry} material={nodes.cube_15.material} />
      <mesh geometry={nodes.cube_16.geometry} material={nodes.cube_16.material} />
      <mesh geometry={nodes.cube_17.geometry} material={nodes.cube_17.material} />
      <mesh geometry={nodes.cube_18.geometry} material={nodes.cube_18.material} />
      <mesh geometry={nodes.cube_19.geometry} material={nodes.cube_19.material} />
      <mesh geometry={nodes.cube_20.geometry} material={nodes.cube_20.material} />
      <mesh geometry={nodes.cube_21.geometry} material={nodes.cube_21.material} />
      <mesh geometry={nodes.cube_22.geometry} material={nodes.cube_22.material} />
      <mesh geometry={nodes.cube_23.geometry} material={nodes.cube_23.material} />
      <mesh geometry={nodes.cube_24.geometry} material={nodes.cube_24.material} />
      <mesh geometry={nodes.cube_25.geometry} material={nodes.cube_25.material} />
      <mesh geometry={nodes.cube_26.geometry} material={nodes.cube_26.material} />
      <mesh geometry={nodes.cube_27.geometry} material={nodes.cube_27.material} />
      <mesh geometry={nodes.cube_28.geometry} material={nodes.cube_28.material} />
      <mesh geometry={nodes.cube_29.geometry} material={nodes.cube_29.material} />
      <mesh geometry={nodes.cube_30.geometry} material={nodes.cube_30.material} />
      <mesh geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
      <mesh geometry={nodes.mesh_1_1.geometry} material={nodes.mesh_1_1.material} />
      <mesh geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
      <mesh geometry={nodes.mesh_2_1.geometry} material={nodes.mesh_2_1.material} />
      <mesh geometry={nodes.mesh_7.geometry} material={nodes.mesh_7.material} />
      <mesh geometry={nodes.mesh_7_1.geometry} material={nodes.mesh_7_1.material} />
      <mesh geometry={nodes.mesh_7_2.geometry} material={nodes.mesh_7_2.material} />
      <mesh geometry={nodes.mesh_7_3.geometry} material={nodes.mesh_7_3.material} />
      <mesh geometry={nodes.mesh_9.geometry} material={nodes.mesh_9.material} />
      <mesh geometry={nodes.mesh_9_1.geometry} material={nodes.mesh_9_1.material} />
      <mesh geometry={nodes.mesh_9_2.geometry} material={nodes.mesh_9_2.material} />
      <mesh geometry={nodes.mesh_9_3.geometry} material={nodes.mesh_9_3.material} />
    </group>
  )
}

useGLTF.preload('src/assets/textures/pre1.gltf')
