/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 C:\Users\USER\OneDrive\Documentos\TI22\HydroSquad\src\assets\textures\Precipitacion.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pre2(props) {
  const { nodes, materials } = useGLTF('src/assets/textures/pre2.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cube.geometry} material={nodes.cube.material} />
      <mesh geometry={nodes.sphere.geometry} material={nodes.sphere.material} rotation={[-Math.PI, 1.562, -Math.PI]} />
      <mesh geometry={nodes.sphere_1.geometry} material={nodes.sphere_1.material} rotation={[-Math.PI, 1.562, -Math.PI]} />
      <mesh geometry={nodes.sphere_2.geometry} material={nodes.sphere_2.material} rotation={[-Math.PI, 1.562, -Math.PI]} />
      <mesh geometry={nodes.sphere_3.geometry} material={nodes.sphere_3.material} rotation={[-Math.PI, 1.562, -Math.PI]} />
      <mesh geometry={nodes.sphere_4.geometry} material={nodes.sphere_4.material} rotation={[-Math.PI, 1.562, -Math.PI]} />
      <mesh geometry={nodes.sphere_5.geometry} material={nodes.sphere_5.material} rotation={[-Math.PI, 1.562, -Math.PI]} />
      <mesh geometry={nodes.cube_7.geometry} material={nodes.cube_7.material} />
      <mesh geometry={nodes.cube_8.geometry} material={nodes.cube_8.material} />
      <mesh geometry={nodes.cube_9.geometry} material={nodes.cube_9.material} />
      <mesh geometry={nodes.cube_10.geometry} material={nodes.cube_10.material} />
      <mesh geometry={nodes.cube_11.geometry} material={nodes.cube_11.material} />
      <mesh geometry={nodes.cube_12.geometry} material={nodes.cube_12.material} />
      <mesh geometry={nodes.cube_13.geometry} material={nodes.cube_13.material} />
      <mesh geometry={nodes.cube_14.geometry} material={nodes.cube_14.material} />
      <mesh geometry={nodes.cube_15.geometry} material={nodes.cube_15.material} />
      <mesh geometry={nodes.cube_16.geometry} material={nodes.cube_16.material} />
      <mesh geometry={nodes.cube_17.geometry} material={nodes.cube_17.material} />
      <mesh geometry={nodes.cube_18.geometry} material={nodes.cube_18.material} />
      <mesh geometry={nodes.cube_19.geometry} material={nodes.cube_19.material} />
      <mesh geometry={nodes.cube_20.geometry} material={nodes.cube_20.material} />
      <mesh geometry={nodes.cube_21.geometry} material={nodes.cube_21.material} />
      <mesh geometry={nodes.cube_22.geometry} material={nodes.cube_22.material} />
      <mesh geometry={nodes.cube_23.geometry} material={nodes.cube_23.material} />
      <mesh geometry={nodes.cube_24.geometry} material={nodes.cube_24.material} />
      <mesh geometry={nodes.cube_25.geometry} material={nodes.cube_25.material} />
      <mesh geometry={nodes.cube_26.geometry} material={nodes.cube_26.material} />
      <mesh geometry={nodes.cube_27.geometry} material={nodes.cube_27.material} />
      <mesh geometry={nodes.cube_28.geometry} material={nodes.cube_28.material} />
      <mesh geometry={nodes.cube_29.geometry} material={nodes.cube_29.material} />
      <mesh geometry={nodes.cube_30.geometry} material={nodes.cube_30.material} />
      <mesh geometry={nodes.cube_31.geometry} material={nodes.cube_31.material} />
      <mesh geometry={nodes.cube_32.geometry} material={nodes.cube_32.material} />
      <mesh geometry={nodes.cube_33.geometry} material={nodes.cube_33.material} />
      <mesh geometry={nodes.cube_34.geometry} material={nodes.cube_34.material} />
      <mesh geometry={nodes.cube_35.geometry} material={nodes.cube_35.material} />
      <mesh geometry={nodes.cube_36.geometry} material={nodes.cube_36.material} />
      <mesh geometry={nodes.cube_37.geometry} material={nodes.cube_37.material} />
      <mesh geometry={nodes.cube_38.geometry} material={nodes.cube_38.material} />
      <mesh geometry={nodes.cube_39.geometry} material={nodes.cube_39.material} />
      <mesh geometry={nodes.cube_40.geometry} material={nodes.cube_40.material} />
      <mesh geometry={nodes.cube_41.geometry} material={nodes.cube_41.material} />
      <mesh geometry={nodes.cube_42.geometry} material={nodes.cube_42.material} />
      <mesh geometry={nodes.cube_43.geometry} material={nodes.cube_43.material} />
      <mesh geometry={nodes.cube_44.geometry} material={nodes.cube_44.material} />
      <mesh geometry={nodes.cube_45.geometry} material={nodes.cube_45.material} />
      <mesh geometry={nodes.cube_46.geometry} material={nodes.cube_46.material} />
      <mesh geometry={nodes.cube_47.geometry} material={nodes.cube_47.material} />
      <mesh geometry={nodes.cube_48.geometry} material={nodes.cube_48.material} />
      <mesh geometry={nodes.cube_49.geometry} material={nodes.cube_49.material} />
      <mesh geometry={nodes.cube_50.geometry} material={nodes.cube_50.material} />
      <mesh geometry={nodes.cube_51.geometry} material={nodes.cube_51.material} />
      <mesh geometry={nodes.cube_52.geometry} material={nodes.cube_52.material} />
      <mesh geometry={nodes.cube_53.geometry} material={nodes.cube_53.material} />
      <mesh geometry={nodes.cube_54.geometry} material={nodes.cube_54.material} />
      <mesh geometry={nodes.cube_55.geometry} material={nodes.cube_55.material} />
      <mesh geometry={nodes.cube_56.geometry} material={nodes.cube_56.material} />
      <mesh geometry={nodes.cube_57.geometry} material={nodes.cube_57.material} />
      <mesh geometry={nodes.cube_58.geometry} material={nodes.cube_58.material} />
      <mesh geometry={nodes.cube_59.geometry} material={nodes.cube_59.material} />
      <mesh geometry={nodes.cube_60.geometry} material={nodes.cube_60.material} />
      <mesh geometry={nodes.cube_61.geometry} material={nodes.cube_61.material} />
      <mesh geometry={nodes.cube_62.geometry} material={nodes.cube_62.material} />
      <mesh geometry={nodes.cube_63.geometry} material={nodes.cube_63.material} />
      <mesh geometry={nodes.cube_64.geometry} material={nodes.cube_64.material} />
      <mesh geometry={nodes.cube_65.geometry} material={nodes.cube_65.material} />
      <mesh geometry={nodes.cube_66.geometry} material={nodes.cube_66.material} />
      <mesh geometry={nodes.cube_67.geometry} material={nodes.cube_67.material} />
      <mesh geometry={nodes.cube_68.geometry} material={nodes.cube_68.material} />
      <mesh geometry={nodes.cube_69.geometry} material={nodes.cube_69.material} />
      <mesh geometry={nodes.cube_70.geometry} material={nodes.cube_70.material} />
      <mesh geometry={nodes.cube_71.geometry} material={nodes.cube_71.material} />
      <mesh geometry={nodes.cube_72.geometry} material={nodes.cube_72.material} />
      <mesh geometry={nodes.cube_73.geometry} material={nodes.cube_73.material} />
      <mesh geometry={nodes.cube_74.geometry} material={nodes.cube_74.material} />
      <mesh geometry={nodes.cube_75.geometry} material={nodes.cube_75.material} />
      <mesh geometry={nodes.cube_76.geometry} material={nodes.cube_76.material} />
      <mesh geometry={nodes.cube_77.geometry} material={nodes.cube_77.material} />
      <mesh geometry={nodes.cube_78.geometry} material={nodes.cube_78.material} />
      <mesh geometry={nodes.cube_79.geometry} material={nodes.cube_79.material} />
      <mesh geometry={nodes.cube_80.geometry} material={nodes.cube_80.material} />
      <mesh geometry={nodes.cube_81.geometry} material={nodes.cube_81.material} />
      <mesh geometry={nodes.cube_82.geometry} material={nodes.cube_82.material} />
      <mesh geometry={nodes.cube_83.geometry} material={nodes.cube_83.material} />
      <mesh geometry={nodes.cube_84.geometry} material={nodes.cube_84.material} />
      <mesh geometry={nodes.cube_85.geometry} material={nodes.cube_85.material} />
      <mesh geometry={nodes.cube_86.geometry} material={nodes.cube_86.material} />
      <mesh geometry={nodes.cube_87.geometry} material={nodes.cube_87.material} />
      <mesh geometry={nodes.cube_88.geometry} material={nodes.cube_88.material} />
      <mesh geometry={nodes.cube_89.geometry} material={nodes.cube_89.material} />
      <mesh geometry={nodes.cube_90.geometry} material={nodes.cube_90.material} />
      <mesh geometry={nodes.cube_91.geometry} material={nodes.cube_91.material} />
      <mesh geometry={nodes.cube_92.geometry} material={nodes.cube_92.material} />
      <mesh geometry={nodes.cube_93.geometry} material={nodes.cube_93.material} />
      <mesh geometry={nodes.cube_94.geometry} material={nodes.cube_94.material} />
      <mesh geometry={nodes.cube_95.geometry} material={nodes.cube_95.material} />
      <mesh geometry={nodes.cube_96.geometry} material={nodes.cube_96.material} />
      <mesh geometry={nodes.cube_97.geometry} material={nodes.cube_97.material} />
      <mesh geometry={nodes.cube_98.geometry} material={nodes.cube_98.material} />
      <mesh geometry={nodes.cube_99.geometry} material={nodes.cube_99.material} />
      <mesh geometry={nodes.cube_100.geometry} material={nodes.cube_100.material} />
      <mesh geometry={nodes.cube_101.geometry} material={nodes.cube_101.material} />
      <mesh geometry={nodes.cube_102.geometry} material={nodes.cube_102.material} />
      <mesh geometry={nodes.cube_103.geometry} material={nodes.cube_103.material} />
      <mesh geometry={nodes.cube_104.geometry} material={nodes.cube_104.material} />
      <mesh geometry={nodes.cube_105.geometry} material={nodes.cube_105.material} />
      <mesh geometry={nodes.cube_106.geometry} material={nodes.cube_106.material} />
      <mesh geometry={nodes.cube_107.geometry} material={nodes.cube_107.material} />
      <mesh geometry={nodes.cube_108.geometry} material={nodes.cube_108.material} />
      <mesh geometry={nodes.cube_109.geometry} material={nodes.cube_109.material} />
      <mesh geometry={nodes.cube_110.geometry} material={nodes.cube_110.material} />
      <mesh geometry={nodes.cube_111.geometry} material={nodes.cube_111.material} />
      <mesh geometry={nodes.cube_112.geometry} material={nodes.cube_112.material} />
      <mesh geometry={nodes.cube_113.geometry} material={nodes.cube_113.material} />
      <mesh geometry={nodes.cube_114.geometry} material={nodes.cube_114.material} />
      <mesh geometry={nodes.cube_115.geometry} material={nodes.cube_115.material} />
      <mesh geometry={nodes.cube_116.geometry} material={nodes.cube_116.material} />
      <mesh geometry={nodes.cube_117.geometry} material={nodes.cube_117.material} />
      <mesh geometry={nodes.cube_118.geometry} material={nodes.cube_118.material} />
      <mesh geometry={nodes.cube_119.geometry} material={nodes.cube_119.material} />
      <mesh geometry={nodes.cube_120.geometry} material={nodes.cube_120.material} />
      <mesh geometry={nodes.cube_121.geometry} material={nodes.cube_121.material} />
      <mesh geometry={nodes.cube_122.geometry} material={nodes.cube_122.material} />
      <mesh geometry={nodes.cube_123.geometry} material={nodes.cube_123.material} />
      <mesh geometry={nodes.cube_124.geometry} material={nodes.cube_124.material} />
      <mesh geometry={nodes.cube_125.geometry} material={nodes.cube_125.material} />
      <mesh geometry={nodes.cube_126.geometry} material={nodes.cube_126.material} />
      <mesh geometry={nodes.cube_127.geometry} material={nodes.cube_127.material} />
      <mesh geometry={nodes.cube_128.geometry} material={nodes.cube_128.material} />
      <mesh geometry={nodes.cube_129.geometry} material={nodes.cube_129.material} />
      <mesh geometry={nodes.cube_130.geometry} material={nodes.cube_130.material} />
      <mesh geometry={nodes.cube_131.geometry} material={nodes.cube_131.material} />
      <mesh geometry={nodes.cube_132.geometry} material={nodes.cube_132.material} />
      <mesh geometry={nodes.cube_133.geometry} material={nodes.cube_133.material} />
      <mesh geometry={nodes.cube_134.geometry} material={nodes.cube_134.material} />
      <mesh geometry={nodes.cube_135.geometry} material={nodes.cube_135.material} />
      <mesh geometry={nodes.cube_136.geometry} material={nodes.cube_136.material} />
      <mesh geometry={nodes.cube_137.geometry} material={nodes.cube_137.material} />
      <mesh geometry={nodes.cube_138.geometry} material={nodes.cube_138.material} />
      <mesh geometry={nodes.cube_139.geometry} material={nodes.cube_139.material} />
      <mesh geometry={nodes.cube_140.geometry} material={nodes.cube_140.material} />
      <mesh geometry={nodes.cube_141.geometry} material={nodes.cube_141.material} />
      <mesh geometry={nodes.cube_142.geometry} material={nodes.cube_142.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_143.geometry} material={nodes.cube_143.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_144.geometry} material={nodes.cube_144.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_145.geometry} material={nodes.cube_145.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_146.geometry} material={nodes.cube_146.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_147.geometry} material={nodes.cube_147.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_148.geometry} material={nodes.cube_148.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_149.geometry} material={nodes.cube_149.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_150.geometry} material={nodes.cube_150.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_151.geometry} material={nodes.cube_151.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_152.geometry} material={nodes.cube_152.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_153.geometry} material={nodes.cube_153.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_154.geometry} material={nodes.cube_154.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_155.geometry} material={nodes.cube_155.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_156.geometry} material={nodes.cube_156.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_157.geometry} material={nodes.cube_157.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_158.geometry} material={nodes.cube_158.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_159.geometry} material={nodes.cube_159.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_160.geometry} material={nodes.cube_160.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_161.geometry} material={nodes.cube_161.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_162.geometry} material={nodes.cube_162.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_163.geometry} material={nodes.cube_163.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_164.geometry} material={nodes.cube_164.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_165.geometry} material={nodes.cube_165.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_166.geometry} material={nodes.cube_166.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_167.geometry} material={nodes.cube_167.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.cube_168.geometry} material={nodes.cube_168.material} rotation={[0, 1.484, 0]} />
      <mesh geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
      <mesh geometry={nodes.mesh_1_1.geometry} material={nodes.mesh_1_1.material} />
      <mesh geometry={nodes.mesh_1_2.geometry} material={nodes.mesh_1_2.material} />
      <mesh geometry={nodes.mesh_1_3.geometry} material={nodes.mesh_1_3.material} />
      <mesh geometry={nodes.mesh_1_4.geometry} material={nodes.mesh_1_4.material} />
      <mesh geometry={nodes.mesh_1_5.geometry} material={nodes.mesh_1_5.material} />
      <mesh geometry={nodes.mesh_1_6.geometry} material={nodes.mesh_1_6.material} />
      <mesh geometry={nodes.mesh_1_7.geometry} material={nodes.mesh_1_7.material} />
      <mesh geometry={nodes.mesh_1_8.geometry} material={nodes.mesh_1_8.material} />
      <mesh geometry={nodes.mesh_1_9.geometry} material={nodes.mesh_1_9.material} />
      <mesh geometry={nodes.mesh_1_10.geometry} material={nodes.mesh_1_10.material} />
      <mesh geometry={nodes.mesh_1_11.geometry} material={nodes.mesh_1_11.material} />
      <mesh geometry={nodes.mesh_1_12.geometry} material={nodes.mesh_1_12.material} />
      <mesh geometry={nodes.mesh_1_13.geometry} material={nodes.mesh_1_13.material} />
      <mesh geometry={nodes.mesh_1_14.geometry} material={nodes.mesh_1_14.material} />
      <mesh geometry={nodes.mesh_1_15.geometry} material={nodes.mesh_1_15.material} />
      <mesh geometry={nodes.mesh_1_16.geometry} material={nodes.mesh_1_16.material} />
      <mesh geometry={nodes.mesh_1_17.geometry} material={nodes.mesh_1_17.material} />
      <mesh geometry={nodes.mesh_1_18.geometry} material={nodes.mesh_1_18.material} />
      <mesh geometry={nodes.mesh_1_19.geometry} material={nodes.mesh_1_19.material} />
      <mesh geometry={nodes.mesh_1_20.geometry} material={nodes.mesh_1_20.material} />
      <mesh geometry={nodes.mesh_1_21.geometry} material={nodes.mesh_1_21.material} />
      <mesh geometry={nodes.mesh_1_22.geometry} material={nodes.mesh_1_22.material} />
      <mesh geometry={nodes.mesh_1_23.geometry} material={nodes.mesh_1_23.material} />
      <mesh geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
      <mesh geometry={nodes.mesh_2_1.geometry} material={nodes.mesh_2_1.material} />
      <mesh geometry={nodes.mesh_2_2.geometry} material={nodes.mesh_2_2.material} />
      <mesh geometry={nodes.mesh_2_3.geometry} material={nodes.mesh_2_3.material} />
      <mesh geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} />
      <mesh geometry={nodes.mesh_3_1.geometry} material={nodes.mesh_3_1.material} />
      <mesh geometry={nodes.mesh_3_2.geometry} material={nodes.mesh_3_2.material} />
      <mesh geometry={nodes.mesh_3_3.geometry} material={nodes.mesh_3_3.material} />
      <mesh geometry={nodes.mesh_3_4.geometry} material={nodes.mesh_3_4.material} />
      <mesh geometry={nodes.mesh_3_5.geometry} material={nodes.mesh_3_5.material} />
      <mesh geometry={nodes.mesh_3_6.geometry} material={nodes.mesh_3_6.material} />
      <mesh geometry={nodes.mesh_3_7.geometry} material={nodes.mesh_3_7.material} />
      <mesh geometry={nodes.mesh_3_8.geometry} material={nodes.mesh_3_8.material} />
      <mesh geometry={nodes.mesh_3_9.geometry} material={nodes.mesh_3_9.material} />
      <mesh geometry={nodes.mesh_3_10.geometry} material={nodes.mesh_3_10.material} />
      <mesh geometry={nodes.mesh_3_11.geometry} material={nodes.mesh_3_11.material} />
      <mesh geometry={nodes.mesh_3_12.geometry} material={nodes.mesh_3_12.material} />
      <mesh geometry={nodes.mesh_3_13.geometry} material={nodes.mesh_3_13.material} />
      <mesh geometry={nodes.mesh_3_14.geometry} material={nodes.mesh_3_14.material} />
      <mesh geometry={nodes.mesh_3_15.geometry} material={nodes.mesh_3_15.material} />
      <mesh geometry={nodes.mesh_3_16.geometry} material={nodes.mesh_3_16.material} />
      <mesh geometry={nodes.mesh_3_17.geometry} material={nodes.mesh_3_17.material} />
      <mesh geometry={nodes.mesh_3_18.geometry} material={nodes.mesh_3_18.material} />
      <mesh geometry={nodes.mesh_3_19.geometry} material={nodes.mesh_3_19.material} />
      <mesh geometry={nodes.mesh_3_20.geometry} material={nodes.mesh_3_20.material} />
      <mesh geometry={nodes.mesh_3_21.geometry} material={nodes.mesh_3_21.material} />
      <mesh geometry={nodes.mesh_3_22.geometry} material={nodes.mesh_3_22.material} />
      <mesh geometry={nodes.mesh_3_23.geometry} material={nodes.mesh_3_23.material} />
      <mesh geometry={nodes.mesh_4.geometry} material={nodes.mesh_4.material} />
      <mesh geometry={nodes.mesh_4_1.geometry} material={nodes.mesh_4_1.material} />
      <mesh geometry={nodes.mesh_4_2.geometry} material={nodes.mesh_4_2.material} />
      <mesh geometry={nodes.mesh_4_3.geometry} material={nodes.mesh_4_3.material} />
      <mesh geometry={nodes.mesh_5.geometry} material={nodes.mesh_5.material} />
      <mesh geometry={nodes.mesh_5_1.geometry} material={nodes.mesh_5_1.material} />
      <mesh geometry={nodes.mesh_5_2.geometry} material={nodes.mesh_5_2.material} />
      <mesh geometry={nodes.mesh_5_3.geometry} material={nodes.mesh_5_3.material} />
      <mesh geometry={nodes.mesh_5_4.geometry} material={nodes.mesh_5_4.material} />
      <mesh geometry={nodes.mesh_5_5.geometry} material={nodes.mesh_5_5.material} />
      <mesh geometry={nodes.mesh_5_6.geometry} material={nodes.mesh_5_6.material} />
      <mesh geometry={nodes.mesh_5_7.geometry} material={nodes.mesh_5_7.material} />
      <mesh geometry={nodes.mesh_5_8.geometry} material={nodes.mesh_5_8.material} />
      <mesh geometry={nodes.mesh_5_9.geometry} material={nodes.mesh_5_9.material} />
      <mesh geometry={nodes.mesh_5_10.geometry} material={nodes.mesh_5_10.material} />
      <mesh geometry={nodes.mesh_5_11.geometry} material={nodes.mesh_5_11.material} />
      <mesh geometry={nodes.mesh_5_12.geometry} material={nodes.mesh_5_12.material} />
      <mesh geometry={nodes.mesh_5_13.geometry} material={nodes.mesh_5_13.material} />
      <mesh geometry={nodes.mesh_5_14.geometry} material={nodes.mesh_5_14.material} />
      <mesh geometry={nodes.mesh_5_15.geometry} material={nodes.mesh_5_15.material} />
      <mesh geometry={nodes.mesh_5_16.geometry} material={nodes.mesh_5_16.material} />
      <mesh geometry={nodes.mesh_5_17.geometry} material={nodes.mesh_5_17.material} />
      <mesh geometry={nodes.mesh_5_18.geometry} material={nodes.mesh_5_18.material} />
      <mesh geometry={nodes.mesh_5_19.geometry} material={nodes.mesh_5_19.material} />
      <mesh geometry={nodes.mesh_5_20.geometry} material={nodes.mesh_5_20.material} />
      <mesh geometry={nodes.mesh_5_21.geometry} material={nodes.mesh_5_21.material} />
      <mesh geometry={nodes.mesh_5_22.geometry} material={nodes.mesh_5_22.material} />
      <mesh geometry={nodes.mesh_5_23.geometry} material={nodes.mesh_5_23.material} />
      <mesh geometry={nodes.mesh_6.geometry} material={nodes.mesh_6.material} />
      <mesh geometry={nodes.mesh_6_1.geometry} material={nodes.mesh_6_1.material} />
      <mesh geometry={nodes.mesh_6_2.geometry} material={nodes.mesh_6_2.material} />
      <mesh geometry={nodes.mesh_6_3.geometry} material={nodes.mesh_6_3.material} />
      <mesh geometry={nodes.mesh_7.geometry} material={nodes.mesh_7.material} />
      <mesh geometry={nodes.mesh_7_1.geometry} material={nodes.mesh_7_1.material} />
      <mesh geometry={nodes.mesh_7_2.geometry} material={nodes.mesh_7_2.material} />
      <mesh geometry={nodes.mesh_7_3.geometry} material={nodes.mesh_7_3.material} />
      <mesh geometry={nodes.mesh_7_4.geometry} material={nodes.mesh_7_4.material} />
      <mesh geometry={nodes.mesh_7_5.geometry} material={nodes.mesh_7_5.material} />
      <mesh geometry={nodes.mesh_7_6.geometry} material={nodes.mesh_7_6.material} />
      <mesh geometry={nodes.mesh_7_7.geometry} material={nodes.mesh_7_7.material} />
      <mesh geometry={nodes.mesh_7_8.geometry} material={nodes.mesh_7_8.material} />
      <mesh geometry={nodes.mesh_7_9.geometry} material={nodes.mesh_7_9.material} />
      <mesh geometry={nodes.mesh_7_10.geometry} material={nodes.mesh_7_10.material} />
      <mesh geometry={nodes.mesh_7_11.geometry} material={nodes.mesh_7_11.material} />
      <mesh geometry={nodes.mesh_7_12.geometry} material={nodes.mesh_7_12.material} />
      <mesh geometry={nodes.mesh_7_13.geometry} material={nodes.mesh_7_13.material} />
      <mesh geometry={nodes.mesh_7_14.geometry} material={nodes.mesh_7_14.material} />
      <mesh geometry={nodes.mesh_7_15.geometry} material={nodes.mesh_7_15.material} />
      <mesh geometry={nodes.mesh_7_16.geometry} material={nodes.mesh_7_16.material} />
      <mesh geometry={nodes.mesh_7_17.geometry} material={nodes.mesh_7_17.material} />
      <mesh geometry={nodes.mesh_7_18.geometry} material={nodes.mesh_7_18.material} />
      <mesh geometry={nodes.mesh_7_19.geometry} material={nodes.mesh_7_19.material} />
      <mesh geometry={nodes.mesh_7_20.geometry} material={nodes.mesh_7_20.material} />
      <mesh geometry={nodes.mesh_7_21.geometry} material={nodes.mesh_7_21.material} />
      <mesh geometry={nodes.mesh_7_22.geometry} material={nodes.mesh_7_22.material} />
      <mesh geometry={nodes.mesh_7_23.geometry} material={nodes.mesh_7_23.material} />
      <mesh geometry={nodes.mesh_8.geometry} material={nodes.mesh_8.material} />
      <mesh geometry={nodes.mesh_8_1.geometry} material={nodes.mesh_8_1.material} />
      <mesh geometry={nodes.mesh_8_2.geometry} material={nodes.mesh_8_2.material} />
      <mesh geometry={nodes.mesh_8_3.geometry} material={nodes.mesh_8_3.material} />
      <mesh geometry={nodes.mesh_9.geometry} material={nodes.mesh_9.material} />
      <mesh geometry={nodes.mesh_9_1.geometry} material={nodes.mesh_9_1.material} />
      <mesh geometry={nodes.mesh_9_2.geometry} material={nodes.mesh_9_2.material} />
      <mesh geometry={nodes.mesh_9_3.geometry} material={nodes.mesh_9_3.material} />
      <mesh geometry={nodes.mesh_9_4.geometry} material={nodes.mesh_9_4.material} />
      <mesh geometry={nodes.mesh_9_5.geometry} material={nodes.mesh_9_5.material} />
      <mesh geometry={nodes.mesh_9_6.geometry} material={nodes.mesh_9_6.material} />
      <mesh geometry={nodes.mesh_9_7.geometry} material={nodes.mesh_9_7.material} />
      <mesh geometry={nodes.mesh_9_8.geometry} material={nodes.mesh_9_8.material} />
      <mesh geometry={nodes.mesh_9_9.geometry} material={nodes.mesh_9_9.material} />
      <mesh geometry={nodes.mesh_9_10.geometry} material={nodes.mesh_9_10.material} />
      <mesh geometry={nodes.mesh_9_11.geometry} material={nodes.mesh_9_11.material} />
      <mesh geometry={nodes.mesh_9_12.geometry} material={nodes.mesh_9_12.material} />
      <mesh geometry={nodes.mesh_9_13.geometry} material={nodes.mesh_9_13.material} />
      <mesh geometry={nodes.mesh_9_14.geometry} material={nodes.mesh_9_14.material} />
      <mesh geometry={nodes.mesh_9_15.geometry} material={nodes.mesh_9_15.material} />
      <mesh geometry={nodes.mesh_9_16.geometry} material={nodes.mesh_9_16.material} />
      <mesh geometry={nodes.mesh_9_17.geometry} material={nodes.mesh_9_17.material} />
      <mesh geometry={nodes.mesh_9_18.geometry} material={nodes.mesh_9_18.material} />
      <mesh geometry={nodes.mesh_9_19.geometry} material={nodes.mesh_9_19.material} />
      <mesh geometry={nodes.mesh_9_20.geometry} material={nodes.mesh_9_20.material} />
      <mesh geometry={nodes.mesh_9_21.geometry} material={nodes.mesh_9_21.material} />
      <mesh geometry={nodes.mesh_9_22.geometry} material={nodes.mesh_9_22.material} />
      <mesh geometry={nodes.mesh_9_23.geometry} material={nodes.mesh_9_23.material} />
      <mesh geometry={nodes.mesh_10.geometry} material={nodes.mesh_10.material} />
      <mesh geometry={nodes.mesh_10_1.geometry} material={nodes.mesh_10_1.material} />
      <mesh geometry={nodes.mesh_10_2.geometry} material={nodes.mesh_10_2.material} />
      <mesh geometry={nodes.mesh_10_3.geometry} material={nodes.mesh_10_3.material} />
      <mesh geometry={nodes.mesh_11.geometry} material={nodes.mesh_11.material} />
      <mesh geometry={nodes.mesh_11_1.geometry} material={nodes.mesh_11_1.material} />
      <mesh geometry={nodes.mesh_11_2.geometry} material={nodes.mesh_11_2.material} />
      <mesh geometry={nodes.mesh_11_3.geometry} material={nodes.mesh_11_3.material} />
      <mesh geometry={nodes.mesh_11_4.geometry} material={nodes.mesh_11_4.material} />
      <mesh geometry={nodes.mesh_11_5.geometry} material={nodes.mesh_11_5.material} />
      <mesh geometry={nodes.mesh_11_6.geometry} material={nodes.mesh_11_6.material} />
      <mesh geometry={nodes.mesh_11_7.geometry} material={nodes.mesh_11_7.material} />
      <mesh geometry={nodes.mesh_11_8.geometry} material={nodes.mesh_11_8.material} />
      <mesh geometry={nodes.mesh_11_9.geometry} material={nodes.mesh_11_9.material} />
      <mesh geometry={nodes.mesh_11_10.geometry} material={nodes.mesh_11_10.material} />
      <mesh geometry={nodes.mesh_11_11.geometry} material={nodes.mesh_11_11.material} />
      <mesh geometry={nodes.mesh_11_12.geometry} material={nodes.mesh_11_12.material} />
      <mesh geometry={nodes.mesh_11_13.geometry} material={nodes.mesh_11_13.material} />
      <mesh geometry={nodes.mesh_11_14.geometry} material={nodes.mesh_11_14.material} />
      <mesh geometry={nodes.mesh_11_15.geometry} material={nodes.mesh_11_15.material} />
      <mesh geometry={nodes.mesh_11_16.geometry} material={nodes.mesh_11_16.material} />
      <mesh geometry={nodes.mesh_11_17.geometry} material={nodes.mesh_11_17.material} />
      <mesh geometry={nodes.mesh_11_18.geometry} material={nodes.mesh_11_18.material} />
      <mesh geometry={nodes.mesh_11_19.geometry} material={nodes.mesh_11_19.material} />
      <mesh geometry={nodes.mesh_11_20.geometry} material={nodes.mesh_11_20.material} />
      <mesh geometry={nodes.mesh_11_21.geometry} material={nodes.mesh_11_21.material} />
      <mesh geometry={nodes.mesh_11_22.geometry} material={nodes.mesh_11_22.material} />
      <mesh geometry={nodes.mesh_11_23.geometry} material={nodes.mesh_11_23.material} />
      <mesh geometry={nodes.mesh_12.geometry} material={nodes.mesh_12.material} />
      <mesh geometry={nodes.mesh_12_1.geometry} material={nodes.mesh_12_1.material} />
      <mesh geometry={nodes.mesh_12_2.geometry} material={nodes.mesh_12_2.material} />
      <mesh geometry={nodes.mesh_12_3.geometry} material={nodes.mesh_12_3.material} />
    </group>
  )
}

// useGLTF.preload('src/assets/textures/pre2.gltf')
useGLTF.preload('/pre2.gltf')
