/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 cyclewater.gltf --transform 
Files: cyclewater.gltf [362.26KB] > cyclewater-transformed.glb [3.69MB] (-918%)
Author: alexvladimircm (https://sketchfab.com/alexvladimircm)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ciclo-del-agua-585a3c7a3dfe4048afa49a3abbe5bbfa
Title: Ciclo Del Agua
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { OrbitControls, Stars } from "@react-three/drei"


export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/cyclewater-transformed.glb')
  const { actions, names } = useAnimations(animations, group)
  // Con esto podemos obtener los modos de animacion
  console.log(names);

  useEffect(() => {
    actions[names[1]].reset().fadeIn(0.5).play();
  }, [])

  return (
    <>
      <ambientLight intensity={2} />
      <mesh scale={[2, 2, 2]}>
        <group ref={group} {...props} dispose={null}>
          <group name="Sketchfab_Scene">
            <primitive object={nodes.GLTF_created_0_rootJoint} />
            <skinnedMesh name="Object_91" geometry={nodes.Object_91.geometry} material={materials.material_0} skeleton={nodes.Object_91.skeleton} scale={0.143} />
            <skinnedMesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.material_1} skeleton={nodes.Object_94.skeleton} scale={0.143} />
            <skinnedMesh name="Object_97" geometry={nodes.Object_97.geometry} material={materials.material_1} skeleton={nodes.Object_97.skeleton} scale={0.143} />
            <skinnedMesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.material_1} skeleton={nodes.Object_100.skeleton} scale={0.143} />
            <skinnedMesh name="Object_103" geometry={nodes.Object_103.geometry} material={materials.material_4} skeleton={nodes.Object_103.skeleton} scale={0.143} />
            <skinnedMesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.material_4} skeleton={nodes.Object_106.skeleton} scale={0.143} />
            <skinnedMesh name="Object_109" geometry={nodes.Object_109.geometry} material={materials.material_4} skeleton={nodes.Object_109.skeleton} scale={0.143} />
            <skinnedMesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.material_4} skeleton={nodes.Object_112.skeleton} scale={0.143} />
            <skinnedMesh name="Object_115" geometry={nodes.Object_115.geometry} material={materials.material_4} skeleton={nodes.Object_115.skeleton} scale={0.143} />
            <skinnedMesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.material_4} skeleton={nodes.Object_118.skeleton} scale={0.143} />
          </group>
        </group>

        <OrbitControls
          enableZoom={false}
          enablePan={true}
          enableRotate={true}
          zoomSpeed={0.6}
          panSpeed={0.5}
          rotateSpeed={0.4}
        />
      </mesh>
    </>
  )
}

useGLTF.preload('/cyclewater-transformed.glb')
